def CONTINUE_BUILD = true
pipeline {
    agent any
    stages {
        stage('Validation') {
            steps {
                dir('project-dummy-1') {
                    script {
                        // def strCount = sh(returnStdout: true, script: "git diff --name-only ${env.GIT_COMMIT} ${GIT_PREVIOUS_SUCCESSFUL_COMMIT} | grep project-dummy-1 | wc -l").trim()
                        def strCount = "1"
                        if(strCount=="0") {
                            echo "Skipping build no files updated"
                            CONTINUE_BUILD = false
                        } else {
                            echo "Changes found in dummy-1 module"
                        }
                    }
                }
            }
        }

        stage('Build') {
            when {
                expression { CONTINUE_BUILD == true }
            }
            steps {
                sh 'echo "Build done for dummy-1"'
            }
        }
        stage('Test') {
            when {
                expression { CONTINUE_BUILD == true }
            }
            steps {
                sh 'echo "Test done for dummy-1"'
            }
        }
        stage('Deliver') { 
            when {
                expression { CONTINUE_BUILD == true }
            }
            steps {
                sh 'echo "Delivery done for dummy-1"'
            }
        }
    }
}
