pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 5051:5051'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'pwd'
                sh 'ls $pwd'
            }
        }
        stage('Test') {
            steps {
                sh 'npm config set fetch-retry-mintimeout 20000'
                sh 'npm config set fetch-retry-maxtimeout 120000'
                sh 'npm update --force --verbose'
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
                input message: 'Finished using the web site? (Click "Proceed" to continue)' 
                sh './jenkins/scripts/kill.sh' 
            }
        }
    }
}
